### ISSUE TITLE
Display in library list whether library is currently open

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#211]
For some libraries we know the opening hours. It would be nice to provide a small label 'open now' or something in the list view, to eliminate the need to open alot.

**Comment by niknetniko** [comment]
This is a bit harder than it seems, because:
1. The hours returned by the API must be parsed (example: http://widgets.lib.ugent.be/libraries/BIB/calendar.json?pretty=1)
2. The opening hours are a seperate request for every library. There is no big list of all hours (that I know of). It might be better to only show this for libraries that are favourites, for example.

**Comment by wschella** [comment]
Valid points. I agree with your solution.

**Comment by niknetniko** [comment]
Implemented for the favourite libraries in #275. The app just displays the hours we get from the API, so we don't have to parse them.
