### ISSUE TITLE
Use new endpoints

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/hydra-android#220]
https://github.com/ZeusWPI/hydra/pull/255, https://github.com/ZeusWPI/hydra/pull/252, https://github.com/ZeusWPI/hydra/pull/253

**Comment by niknetniko** [comment]
This is issues has been fixed in:
- https://github.com/ZeusWPI/hydra/pull/255: this uses the same endpoint, so no changes needed at our end.
- https://github.com/ZeusWPI/hydra/pull/252: will be fixed with #225 
- https://github.com/ZeusWPI/hydra/pull/253: fixed in #223 
- Urgent.fm now also uses the API at https://zeus.ugent.be/hydra/api/2.0/urgentfm/status.json, with #226
