### ISSUE TITLE
Pressing the 'scan' button in Zeus mode gives a 'Network failure' toast

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/hydra-android#607]
Manually searching and ordering the item does work

**Comment by niknetniko** [comment]
When pressing the scan button, the barcodes and products are loaded from the network. If one of those requests fail for whatever reason, the scan activity is closed, as it won't work anyway, since the product will not be recognised. I suspect there must have been a temporary network issue or server issue with Tap.

**Comment by redfast00** [comment]
It still does not work, with the same error message

**Comment by niknetniko** [comment]
Then I'll need logcat to determine what the issue is, as I can't reproduce it.

**Comment by redfast00** [comment]
Guess I'll get out of my couch to go look for a USB cable then

**Comment by redfast00** [comment]
Apparently I don't have the correct proprietary Google *bucht*

**Comment by niknetniko** [comment]
> Apparently I don't have the correct proprietary Google _bucht_

Maybe I can interest you in the _open_ version of the app?
